DROP TABLE IF EXISTS productify_projects;

CREATE TABLE productify_projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    projectName TEXT NOT NULL,
    teamId INTEGER REFERENCES productify_teams(id) ON DELETE CASCADE NOT NULL
);