DROP TABLE IF EXISTS productify_users_info;

CREATE TABLE productify_users_info (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    jobTitle TEXT NOT NULL,
    teamId INTEGER REFERENCES productify_teams(id) ON DELETE CASCADE NOT NULL
);